application: bnterprofiler
version: 3
runtime: python
api_version: 1

handlers:
   
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
   
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))
  
- url: /.*
  script: py/main.py